config/routes.rb
Rails.application.routes.draw do
  get "users" => "users#index"
  post "users" => "users#create"
  get "users/new" => "users#new"
  get "users/:id/edit" => "users#edit", as: "edit_user"
  get "users/:id" => "users#show", as: "user"
  patch "users/:id" => "users#update"
  put "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :pets do
    resources :posts do
      resources :comments
    end
  end

  root "sessions#new"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_presence :image
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :pet
  has_many :comments, dependent: :destroy
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_presence :image
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :pets, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates_attachment_presence :image
	validates :name, presence: true
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates :password, presence: true, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_comment, only: [:show, :edit, :update, :destroy]

	def index
		@comments = Comment.all
	end

	def show
		@comments = Comment.find(params[:id])
	end

	def new
		if session[:user_id] != nil
			@comment = Comment.new
			@pet = Pet.find(params[:pet_id])
			@post = Post.find(params[:post_id])
			@user = User.find(session[:user_id])
		else
			redirect_to root_path
		end
	end

	def create
		@user = User.find(session[:user_id])
		@pet = Pet.find(params[:pet_id])
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		@comment.user_id = @user.id
		@comment.save
		redirect_to pet_post_path(params[:pet_id],params[:post_id])
	end

	def destroy
		@comment.destroy
		respond_to do |format|
	      	format.html { redirect_to pets_url, notice: 'comment successfully deleted.' }
	      	format.json { head :no_content }
	    end
	end

private

	def set_comment
		@comment = comment.find(params[:id])
	end

	def comment_params
	    params.require(:comment).permit(:body, :post_id, :user_id)
	end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

	before_action :set_pet, only: [:show, :edit, :update, :destroy]

	def index
		@pets = Pet.all
		# makes the modal work for adding a new pet
		@pet = Pet.new
	end

	def show
		@pet = Pet.find(params[:id])
		@posts = Post.where(pet_id: @pet.id)
	end

	def new
		@pet = Pet.new
	end

	def create
		@user = User.find(session[:user_id])
    	@pet = @user.pets.create(pet_params)
	    @pet = Pet.new(pet_params)
	    # raise @pet.inspect
	    redirect_to pets_path
	end

	def edit
		@pet = Pet.find(params[:id])
	end

	def update
		@pet = Pet.find(params[:id])
		respond_to do |format|
			if @pet.update(pet_params)
				format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        		format.json { render :show, status: :ok, location: @pet }
        	else
        		format.html { render :edit }
        		format.json { render json: @pet.errors, status: :unprocessable_entity }
      		end
      	end
	end

	def destroy
		@pet.destroy
	    respond_to do |format|
	      	format.html { redirect_to pets_url, notice: 'Pet profile successfully deleted.' }
	      	format.json { head :no_content }
	    end
	end

private

	def set_pet
		@pet = Pet.find(params[:id])
	end

	def pet_params
	    params.require(:pet).permit(:name, :birthday, :photo, :description, :user_id, :image)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def show
		@pet = Pet.find(params[:pet_id])
		@posts = Post.find(params[:id])
		@comments = Comment.where(post_id: @post.id)
	end

	def new
		if session[:user_id] != nil
			@post = Post.new
			@user = User.find(session[:user_id])
			@pet = Pet.find(params[:pet_id])
			@pets = Pet.where(user_id: @user.id)
		else
			redirect_to root_path
		end
	end

	def edit
		if session[:user_id] == nil
			redirect_to root_path
		end
	end

	def create
		@user = User.find(session[:user_id])
		@pet = Pet.find(params[:pet_id])
		@pets = Pet.where(user_id: @user.id)
		@post = Post.new(post_params)
		@post.save
		redirect_to pet_path(@pet)
	end

	def update 
		respond_to do |format|
			if @post.update(post_params)
				format.html { redirect_to pet_post_path(@pet, @post), notice: 'Post was successfully updated.' }
        		format.json { render :show, status: :ok, location: @pet }
        	else
        		format.html { render :edit }
        		format.json { render json: @post.errors, status: :unprocessable_entity }
      		end
      	end
	end

	def destroy
		@post.destroy
		respond_to do |format|
	      	format.html { redirect_to pets_url, notice: 'Post successfully deleted.' }
	      	format.json { head :no_content }
	    end
	end

private

	def set_post
		@pet = Pet.find(params[:pet_id])
		@post = Post.find(params[:id])
	end

	def post_params
	    params.require(:post).permit(:title, :body, :image, :pet_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
      @pets = Pet.all
  	end

  	def create
  		user = User.find_by(email: params[:login][:email])
	    if user && user.authenticate(params[:login][:password])
	      	session[:user_id] = user.id.to_s
          redirect_to pets_path
          flash[:notice] = "Welcome to Petnet!"
	    else
          render "new"
	      	# @error = "Email and password do not match"
	    end
  	end

  	def destroy
  		session.delete(:user_id)
      redirect_to login_path
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all
		# makes the modal work for adding a new pet
		@pet = Pet.new
	end

	def show
		@pets = Pet.where(user_id: @user.id)
		# makes the modal work for adding a new pet
		@pet = Pet.new
	end

	def new
		@user = User.new
	end

	def edit
		
	end

	def create
	    @user = User.new(user_params)
	    if @user.save
	      	redirect_to users_path
	      	session[:user_id] = @user.id.to_s
	    else
	      render :new
	    end
	end

	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to @user, notice: "Your profile was successfully updated." }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@user.destroy
		redirect_to users_path
	end

private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
	    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
  		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [@pet, @post, @comment] do |f| %>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/comments/new.html.erb
<h1>Add a comment!</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petnet</title>
  <%= favicon_link_tag 'default.jpg' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar nav-blue">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="pets">Petnet</a>
    </div>
        <%= link_to "View Pets", pets_path, {class: "btn btn-default navbar-btn navbar-left"} %>
        <%= link_to "View Pet Parents", users_path, {class: "btn btn-default navbar-btn navbar-left"} %>
        <% if current_user %>
            <button type="button" class="btn btn-default navbar-btn navbar-right"><%= link_to 'Log Out', logout_path, method: :delete %></button>
            <%= link_to "Logged in as: " + current_user.name, user_path(current_user), {class: "btn btn-default navbar-btn navbar-right"} %>
        <% else %>
            <%= link_to 'Log In', login_path, {class: "btn btn-default navbar-btn navbar-right"} %>
            <%= link_to 'Sign Up', users_new_path, {class: "btn btn-default navbar-btn navbar-right"} %>
        <% end %>
    </div>
  </div>
</nav>

<div class="container">

  <% if flash[:notice] %>
    <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
  <% end %>

  <%= yield %>

</div>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
    <div class="form-group shrink">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div class="form-group shrink">
        <%= f.label :birthday %>
        <%= f.date_field :birthday %>
    </div>
    <div class="form-group shrink">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>
    <div class="form-group shrink">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div class="shrink">
        <%= f.submit %>
    </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit your pet's profile</h1>

<%= render 'form' %>

app/views/pets/index.html.erb
<% if current_user %>
  <h1>Petnet Pets
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add a new pet profile</button>
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Add a new pet profile</h4>
                </div>
              <div class="modal-body">
              <%= render 'form' %>
              </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>
          </div>
      </div>
  </h1>
<% else %>
  <h1>Petnet Pets</h1>
  <p><%= link_to "Log in", login_path %> or <%= link_to "sign up", users_new_path %> to add a pet profile!</p>
<% end %>
<table class="table table-hover">
  	<thead>
    	<tr>
	      	<th>Name</th>
	      	<th>Photo</th>
	      	<th>Description</th>
	      	<th>Birthday</th>
	      	<th>Parent</th>
	      	<th colspan="3"></th>
    	</tr>
  	</thead>

  	<tbody>
    	<% @pets.each do |pet| %>
      	<tr>
          <td><%= link_to pet.name, pet %></td>
	        <td>
            <% if pet.image_file_name == nil && pet.user.image_file_name == nil %>
              <%= link_to (image_tag 'default.jpg'), pet %>
            <% elsif pet.image_file_name == nil %>
              <%= link_to (image_tag pet.user.image.url(:small)), pet %>
            <% else %>
              <%= link_to (image_tag pet.image.url(:small)), pet %>
            <% end %>
          </td>
	        <td><%= pet.description %></td>
	        <td><%= pet.birthday %></td>
            <% if pet.user %>
                <td><%= link_to pet.user.name, pet.user %></td>
            <% end %>
      	</tr>
    	<% end %>
  	</tbody>
</table>

app/views/pets/new.html.erb
<h1>Add your pet</h1>

<%= render 'form' %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @pet.name %>
	<% if @pet.user == current_user %>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Edit <%= @pet.name %>'s profile</button>
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  	<div class="modal-dialog">
		    	<div class="modal-content">
		      		<div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Edit <%= @pet.name %>'s profile</h4>
		      		</div>
		      	<div class="modal-body">
		        <%= render 'form' %>
		      	</div>
		      		<div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
		      		</div>
		    	</div>
		  	</div>
		</div>
	<% end %>
</h2>

<% if @pet.birthday %>
	<h5>is <%= time_ago_in_words(@pet.birthday) %> old</h5>
<% end %>

<p>
	<% if @pet.image_file_name == nil && @pet.user.image_file_name == nil %>
		<%= image_tag 'default.jpg' %>
	<% elsif @pet.image_file_name == nil %>
		<%= image_tag @pet.user.image.url(:large) %>
	<% else %>
		<%= image_tag @pet.image.url(:large) %>
	<% end %>
</p>

<div class="border">
	<%= @pet.description %>
</div>

<button type="button" class="btn btn-default">
	<strong>Parent:</strong>
	<%= link_to @pet.user.name, @pet.user %>
</button>

<br><br>

<h2><%= @pet.name %>'s Posts</h2>

<% if @pet.user == current_user %>
	<button type="button" class="btn btn-default">
		<%= link_to 'Add a New Post', new_pet_post_path(@pet) %>
	</button>
<% end %>

<div class="border">
	<% if @posts.count > 0 %>
		<% @posts.each do |post| %>
			<h4><%= link_to post.title, pet_post_path(@pet, post) %></h4>

			<p>
				<% if post.image_file_name == nil && post.pet.image_file_name == nil && post.pet.user.image_file_name == nil %>
					<%= link_to (image_tag 'default.jpg'), pet_post_path(@pet, post) %>
				<% elsif post.image_file_name == nil && post.pet.image_file_name == nil %>
					<%= link_to (image_tag post.pet.user.image.url(:large)), pet_post_path(@pet, post) %>
				<% elsif post.image_file_name == nil %>
					<%= link_to (image_tag post.pet.image.url(:large)), pet_post_path(@pet, post) %>
				<% else %>
					<%= link_to (image_tag post.image.url(:large)), pet_post_path(@pet, post) %>
				<% end %>
			</p>
		<% end %>
	<% else %>
		<%= @pet.name %> doesn't have any posts yet.
	<% end %>
</div>

<% if @pet.user == current_user %>
	<button class="btn btn-danger delete">
		<%= link_to 'Delete Pet Profile', @pet, method: :delete, data: { confirm: 'Are you sure?' } %>
	</button>
<% end %>

app/views/posts/_form.html.erb
<%= form_for [@pet, @post] do |f| %>
    <div class="form-group shrink">
        <%= f.label :pet_id %>
        <%= f.collection_select(:pet_id, @pets.all, :id, :name) %>
    </div>
    <div class="form-group shrink">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div class="form-group shrink">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>
    <div class="form-group shrink">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <div class="shrink">
        <%= f.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit <%= @pet.name %>'s post</h1>

<%= form_for [@pet, @post] do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<table class="table table-hover">
  	<thead>
    	<tr>
	      	<th>Posted by</th>
	      	<th>Title</th>
	      	<th>Image</th>
	      	<th>Body</th>
	      	<th colspan="3"></th>
    	</tr>
  	</thead>

  	<tbody>
    	<% @posts.each do |post| %>
      	<tr>
            <td><% if post.pet %>
            	<%= link_to post.pet.name, post.pet %>
            	<% end %>
            </td>
	        <td><%= post.title %></td>
	        <td><%= link_to (image_tag post.image.url(:small)), post.pet %></td>
	        <td><%= post.body %></td>
      	</tr>
    	<% end %>
  	</tbody>
</table>

app/views/posts/new.html.erb
<h1>Add a new post</h1>


<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
	<% if @post.pet %>
        <%= link_to @post.pet.name, @post.pet %>
    <% end %>
    <% if @pet.user == current_user %>
	    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Edit this post</button>
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  	<div class="modal-dialog">
		    	<div class="modal-content">
		      		<div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Edit this post</h4>
		      		</div>
		      	<div class="modal-body">
		        <h1>Edit <%= @pet.name %>'s post</h1>
					<%= form_for [@pet, @post] do |f| %>
					    <div class="form-group shrink">
					        <%= f.label :title %>
					        <%= f.text_field :title %>
					    </div>
					    <div class="form-group shrink">
					        <%= f.label :image %>
					        <%= f.file_field :image %>
					    </div>
					    <div class="form-group shrink">
					        <%= f.label :body %>
					        <%= f.text_area :body %>
					    </div>
					    <div class="shrink">
					        <%= f.submit %>
					    </div>
					<% end %>
		      	</div>
		      		<div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
		      		</div>
		    	</div>
		  	</div>
		</div>
	<% end %>
</h2>

<h4>
  	<%= @post.title %>
</h4>

<p>
	<% if @post.image_file_name == nil && @post.pet.image_file_name == nil && @post.pet.user.image_file_name == nil %>
		<%= image_tag 'default.jpg' %>
	<% elsif @post.image_file_name == nil && @post.pet.image_file_name == nil %>
		<%= image_tag @post.pet.user.image.url(:large) %>
	<% elsif @post.image_file_name == nil %>
		<%= image_tag @post.pet.image.url(:large) %>
	<% else %>
		<%= image_tag @post.image.url(:large) %>
	<% end %>
</p>

<p>
  	<%= @post.body %>
</p>

<% @comments.each do |comment| %>
	<div class="border">
		<p>
		  	<%= link_to comment.user.name, comment.user %> says:
		  	<%= comment.body %>
		</p>
	</div>
<% end %>

<% if current_user %>
	<button type="button" class="btn btn-default">
		<%= link_to 'Add a comment', new_pet_post_comment_path(@pet, @post) %>
	</button>
<% else %>
	<%= link_to "Log in", login_path %> to comment on this post!
<% end %>

<% if @post.pet.user == current_user %>
	<div class="btn btn-danger delete">
		<%= link_to 'Delete this post', pet_post_path(@pet, @post), method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <div class="form-group shrink">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div class="form-group shrink">
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>
    <div class="form-group shrink">
        <%= f.label :image %>
        <%= f.file_field :image%>
    </div>

    <div class="form-group shrink">
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div class="form-group shrink">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="shrink">
        <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<% if current_user %>
  <h1>Pet Parents
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add a new pet profile</button>
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Add a new pet profile</h4>
                </div>
              <div class="modal-body">
              <%= render 'pets/form' %>
              </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>
          </div>
      </div>
  </h1>
<% else %>
  <h1>Petnet Pets</h1>
  <p><%= link_to "Log in", login_path %> or <%= link_to "sign up", users_new_path %> to add a pet profile!</p>
<% end %>
<table class="table table-hover">
  	<thead>
    	<tr>
	      	<th>Name</th>
          <th>Photo</th>
	      	<th>Member for</th>
	      	<th colspan="3"></th>
    	</tr>
  	</thead>

  	<tbody>
    	<% @users.each do |user| %>
      	<tr>
	        <td><%= link_to user.name, user %></td>
          <td>
            <% if user.image_file_name == nil %>
              <%= link_to (image_tag 'default.jpg'), user %>
            <% else %>
              <%= link_to (image_tag user.image.url(:small)), user %>
            <% end %>
          </td>
	        <td><%= time_ago_in_words(user.created_at) %></td>
      	</tr>
    	<% end %>
  	</tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<h5>1. Set up your pet parent profile</h5>
<h5>2. Set up profiles for all of your pets</h5>
<h5>3. Post on your pet's profile and comment on other pets' posts</h5>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  	<%= @user.name %>
	<% if @user == current_user %>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Edit your profile</button>
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  	<div class="modal-dialog">
		    	<div class="modal-content">
		      		<div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Edit your profile</h4>
		      		</div>
		      	<div class="modal-body">
		        <%= render 'form' %>
		      	</div>
		      		<div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
		      		</div>
		    	</div>
		  	</div>
		</div>
	<% end %>
</h2>

<p>
	<% if @user.image_file_name == nil %>
		<%= image_tag 'default.jpg' %>
	<% else %>
		<%= image_tag @user.image.url(:large) %>
	<% end %>
</p>

<p>
  	<button type="button" class="btn btn-default">
  		<%= mail_to @user.email, @user.email %>
  	</button>
</p>

<br>

<h2><%= @user.name %>'s Pets
	<% if @user == current_user %>
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add a new pet profile</button>
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		  	<div class="modal-dialog">
		    	<div class="modal-content">
		      		<div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Add a new pet profile</h4>
		      		</div>
		      	<div class="modal-body">
		        <%= render 'pets/form' %>
		      	</div>
		      		<div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
		      		</div>
		    	</div>
		  	</div>
		</div>
	<% end %>
</h2>

<% @pets.each do |pet| %>
	<div class="border">
		<button type="button" class="btn btn-default">
		  	<%= link_to pet.name, pet %>
		</button>
		<br><br>
		<p>
			<% if pet.image_file_name == nil && pet.user.image_file_name == nil %>
				<%= link_to (image_tag 'default.jpg'), pet %>
			<% elsif pet.image_file_name == nil %>
				<%= link_to (image_tag pet.user.image.url(:large)), pet %>
			<% else %>
				<%= link_to (image_tag pet.image.url(:large)), pet %>
			<% end %>
		</p>
	</div>
<% end %>

<% if @user == current_user %>
	<div class="btn btn-danger delete">
		<%= link_to 'Delete Profile', @login, method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
<% end %>